# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMayor',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoDespreciable',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('vidaUtil', models.IntegerField()),
                ('valorRecuperacion', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('debe', models.BooleanField()),
                ('cantidad', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoMp',
            fields=[
                ('idMov', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('precioUnitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ordenDeFabricacion',
            fields=[
                ('numOrden', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fechaExpedicion', models.DateField(default='2000-01-01')),
                ('fechaRequerida', models.DateField(default='2000-01-01')),
                ('materal', models.CharField(max_length=100)),
                ('catidadMP', models.FloatField(default=0.0)),
                ('costoUnitarioMP', models.FloatField(default=0.0)),
                ('numHoras', models.IntegerField()),
                ('costoHora', models.FloatField(default=0.0)),
                ('tasaCIF', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('numProducto', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('inventarioInicialMp', models.FloatField(default=0.0)),
                ('compras', models.FloatField(default=0.0)),
                ('inventarioFinal', models.FloatField(default=0.0)),
                ('invIniPenP', models.FloatField(default=0.0)),
                ('invFinalPenP', models.FloatField(default=0.0)),
                ('invInicialProductTerminado', models.FloatField(default=0.0)),
                ('invFinalProductTerminado', models.FloatField(default=0.0)),
                ('nuneroArticulos', models.IntegerField(default=0.0)),
                ('ordenDeFabricacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ordenDeFabricacion')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=10, null=True)),
                ('monto', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='acreedor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puesto',
            name='salarioNominalDiario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigo',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='debe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='haber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='rubro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rubro'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoFinal',
            field=models.FloatField(verbose_name=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoInicial',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='codigo',
            field=models.CharField(default='111', max_length=5),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoTransaccion'),
        ),
        migrations.AddField(
            model_name='ordendefabricacion',
            name='obrero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaccion'),
        ),
        migrations.AddField(
            model_name='equipodespreciable',
            name='cuentaValorCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta'),
        ),
        migrations.AddField(
            model_name='equipodespreciable',
            name='depreciacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Depreciacion'),
        ),
        migrations.AddField(
            model_name='depreciacion',
            name='cuentaLibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuentaMayor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CuentaMayor'),
        ),
    ]
