# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-04 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
