# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=5, max_digits=5)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoTransaccion')),
            ],
        ),
    ]
