# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161120_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMayor',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
    ]
