# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TipoCuenta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoTransaccion'),
        ),
    ]
