# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-12 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaccion'),
        ),
    ]
