# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161122_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciacion',
            name='cantidad',
            field=models.FloatField(max_length=50),
        ),
    ]
