# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161126_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipodespreciable',
            name='valorActual',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
