# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cuentamayor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cuentaMayor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CuentaMayor'),
        ),
    ]
