# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161112_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='debe',
            field=models.BooleanField(default=1),
        ),
    ]
