# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161106_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='proveedor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Proveedor'),
        ),
    ]
