# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cuenta_cuentamayor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salarioNominalDiario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
