# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cuenta_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comentario',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
