# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161114_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
