# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transaccion_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
