# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161114_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
