# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161106_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Proveedor'),
        ),
    ]
