# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161117_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='haber',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoFinal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoInicial',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
