# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161117_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='acreedor',
            field=models.BooleanField(default=True),
        ),
    ]
