# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161112_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='proveedor',
        ),
    ]
