# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161121_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
