# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161121_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=50)),
                ('cuentaLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoDespreciable',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('vidaUtil', models.IntegerField()),
                ('valorRecuperacion', models.FloatField(default=0.0)),
                ('cuentaValorCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta')),
                ('depreciacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Depreciacion')),
            ],
        ),
    ]
