# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cuenta_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=21)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Rubro'),
        ),
    ]
