# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161117_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='debe',
            field=models.BooleanField(),
        ),
    ]
