# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161113_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('debe', models.BooleanField()),
                ('cantidad', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prestacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentage', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='acreedor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='codigo',
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='puesto',
            name='salarioNominalDiario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tipocuenta',
            name='codigo',
            field=models.CharField(default='111', max_length=5),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='descripcion',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='debe',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='haber',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoFinal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoInicial',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoCuenta'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipotransaccion',
            name='nombre',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cuenta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaccion'),
        ),
    ]
