# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161118_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='debe',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='haber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoFinal',
            field=models.FloatField(verbose_name=0.0),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldoInicial',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='porcentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salarioNominalDiario',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.FloatField(default=0.0),
        ),
    ]
