# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161117_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='porcentage',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salario',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
