# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161118_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenDeFabricacion',
            fields=[
                ('numOrden', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('materal', models.CharField(max_length=100)),
                ('catidadMP', models.FloatField(default=0.0)),
                ('costoUnitarioMP', models.FloatField(default=0.0)),
                ('numHoras', models.IntegerField()),
                ('costoHora', models.FloatField(default=0.0)),
                ('tasaCIF', models.FloatField(default=0.0)),
                ('obrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado')),
            ],
        ),
    ]
