# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161117_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
