# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-17 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20161117_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puesto',
            old_name='salario',
            new_name='salarioNominalDiario',
        ),
    ]
