# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-17 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20161117_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
